### ISSUE TITLE
启动之后报错Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by Selinng** [57code/vite2-in-action#1]
![image](https://user-images.githubusercontent.com/32927500/107140506-6ad2b180-695d-11eb-98d2-b031cb84a227.png)
![image](https://user-images.githubusercontent.com/32927500/107140515-7d4ceb00-695d-11eb-98ed-e2649edae89a.png)

系统： windows
cpu：i7 8代

**Comment by qw789** [comment]
我也是一样。麻烦开发者解决一下

**Comment by 57code** [comment]
我没办法重现这个问题，我在自己的windows电脑上没有出现这个情况

**Comment by 57code** [comment]
> 我没办法重现这个问题，我在自己的windows电脑上没有出现这个情况

猜测是node版本，位数引起的

**Comment by peng4616** [comment]
我遇到了同那个样问题， 是node版本导致，vite  node版本 需要>=12
![image](https://user-images.githubusercontent.com/28663554/108167794-331ff280-7131-11eb-943b-cfc09032ec89.png)

**Comment by xuebin00** [comment]
node版本12.10.0 会报这个错。我把node升级到14.15.4 同样报错。找了一圈没找着原因 ：(

**Comment by xuebin00** [comment]
放弃使用path ..

**Comment by xuebin00** [comment]
![微信图片_20210217172038](https://user-images.githubusercontent.com/17266744/108183298-e9410780-7144-11eb-81e7-fdbc36c675be.png)
放弃使用path ..

**Comment by qw789** [comment]
> node版本12.10.0 会报这个错。我把node升级到14.15.4 同样报错。找了一圈没找着原因 ：(

我也是一样，node版本15+依旧不行

**Comment by qw789** [comment]
> ![微信图片_20210217172038](https://user-images.githubusercontent.com/17266744/108183298-e9410780-7144-11eb-81e7-fdbc36c675be.png)
> 放弃使用path ..

放弃使用path，那里面引用它的方法咋办

**Comment by xuebin00** [comment]
> 
> 
> > ![微信图片_20210217172038](https://user-images.githubusercontent.com/17266744/108183298-e9410780-7144-11eb-81e7-fdbc36c675be.png)
> > 放弃使用path ..
> 
> 放弃使用path，那里面引用它的方法咋办

path本来也是在node环境里运行来配置环境变量的，那块业务逻辑跳转可以用相对地址。

**Comment by xuebin00** [comment]
> 
> 
> > ![微信图片_20210217172038](https://user-images.githubusercontent.com/17266744/108183298-e9410780-7144-11eb-81e7-fdbc36c675be.png)
> > 放弃使用path ..
> 
> 放弃使用path，那里面引用它的方法咋办
可以用相对路径，path貌似更多在node环境里用

**Comment by qw789** [comment]
> > > ![微信图片_20210217172038](https://user-images.githubusercontent.com/17266744/108183298-e9410780-7144-11eb-81e7-fdbc36c675be.png)
> > > 放弃使用path ..
> > 
> > 
> > 放弃使用path，那里面引用它的方法咋办
> > 可以用相对路径，path貌似更多在node环境里用

这样改还是不爽啊

**Comment by CHOYSEN** [comment]
问题在于 `path` 这个模块是 nodejs 的，并不存在于浏览器环境。由于 Vite 的解析机制导致这个模块被成功读取了，我不知道这是不是一个正确的行为。模块中使用了 `process` 这个变量，这个变量在之前的 Vite 版本中是被 shim 的（用于读取环境变量），而在 https://github.com/vitejs/vite/commit/8ad7ecd1029bdc0b47e55877db10ac630829c7e5 中这个 shim 被取消了，所以我认为最好不要在代码文件中使用 nodejs 的模块。

@57code

**Comment by qw789** [comment]
> 问题在于 `path` 这个模块是 nodejs 的，并不存在于浏览器环境。由于 Vite 的解析机制导致这个模块被成功读取了，我不知道这是不是一个正确的行为。模块中使用了 `process` 这个变量，这个变量在之前的 Vite 版本中是被 shim 的（用于读取环境变量），而在 [vitejs/vite@8ad7ecd](https://github.com/vitejs/vite/commit/8ad7ecd1029bdc0b47e55877db10ac630829c7e5) 中这个 shim 被取消了，所以我认为最好不要在代码文件中使用 nodejs 的模块。
> 
> @57code

你看package.json里，这里的path是完全基于nodejs的path的一个包，并不是直接引的node的path

**Comment by jaysonwu991** [comment]
Use `path-browserify` to replace `path`, and remove `path` dependency in package.json, it works perfect. More detail sees [57code
/vite2-in-action@e8d139d](https://github.com/57code/vite2-in-action/commit/e8d139d7c2ccdc90d565a921c8880fae011508b6).

**Comment by qw789** [comment]
> Use `path-browserify` to replace `path`, and remove `path` dependency in package.json, it works perfect. More detail sees [57code /vite2-in-action@e8d139d](https://github.com/57code/vite2-in-action/commit/e8d139d7c2ccdc90d565a921c8880fae011508b6).

good job

**Comment by 57code** [comment]
此问题已解决

**Comment by sonicsunsky** [comment]
这个使用path-browserify之后还是会报错processs is not defined

**Comment by jaysonwu991** [comment]
> 这个使用path-browserify之后还是会报错processs is not defined

- First, asking clearly, provide the useful error info, a screenshot or a capture will be helpful a lot.
- Second, provide the system you use and node version you run (including npm), since it won't work if you use a lower version of node below v12+.
- Third, have you try to checkout the latest code and delete `package-lock.json` file and `node_modules` folder before asking? if not, try it first, if the problem is still there, please provide a GitHub repo to repeat the errors.

我是中国人，我以我是中国人而自豪，but using English to ask please, it can help more people from all countries to understand your issue.
